### ISSUE TITLE
Estimation of other variables: SOC, SOH

### ISSUE THREAD

**Issue by davidhernandez-cea** [muizabdul29/PyBatteryID#1]
Hi, first of all very nice work and very interesting approach.
I have some questions about the `simulate` method.
If I understand well it currently only supports predicting voltage values.
But what about other variables of interest as the SOC for example?
More over, what if my `dataset` also has SOH and I want to predict that also?

**Comment by muizabdul29** [comment]
Thank you for your interest. You are absolutely correct that the package only supports voltage simulation at the moment. We do plan to extend the package to support SOC estimation using a state observer (Kalman Filter), in near future. The inclusion of SOH is also in our plans but will require more time. Thanks again.

Note: The paper associated with the package is currently under review, and is expected to come out in one or two months.

**Comment by muizabdul29** [comment]
You can now see the article at the following link: https://www.sciencedirect.com/science/article/pii/S2352152X24021674
